spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://localhost:3306/workoreder?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8004
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka
mybatis:
  type-aliases-package: com.zhibo.springcloud.entity
  mapper-locations: mapper/*.xml